---
- name: wrapper playbook for testing "postgres_hardening" with default settings
  hosts: all
  become: true
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  collections:
    - devsec.hardening
  tasks:
    - include_role:
        name: postgres_hardening
